### ISSUE TITLE
Challenge 5 | Maurício Mutte

### ISSUE THREAD

**Issue by mauriciomutte** [LFeh/felipefriends#10]
# Challenge 5
## Links
- [Link do site](http://mauriciomutte.com)
- [Link do repositório no github](https://github.com/mauriciomutte)

#### Home
![image](https://user-images.githubusercontent.com/20569339/30193459-943320c2-9423-11e7-9528-543f9e266af1.png)

#### Blog
![image](https://user-images.githubusercontent.com/20569339/30193568-370b42a2-9424-11e7-911b-23603ba48a68.png)

#### Post
![image](https://user-images.githubusercontent.com/20569339/30199195-01189630-9448-11e7-8d39-a4af06c47a95.png)

#### Projetos
![image](https://user-images.githubusercontent.com/20569339/30193514-ec3922c6-9423-11e7-97fd-3d87a76d7444.png)

#### Sobre mim
![image](https://user-images.githubusercontent.com/20569339/30193520-f2ea0090-9423-11e7-9443-e8f3f841abc7.png)

#### Home
![image](https://user-images.githubusercontent.com/20569339/30193642-a96e1c02-9424-11e7-8116-801e4f9aaad5.png)

#### Blog
![image](https://user-images.githubusercontent.com/20569339/30193653-b5828a64-9424-11e7-8bb1-444c4f1f4842.png)

#### Post
![image](https://user-images.githubusercontent.com/20569339/30199203-0b75d8d6-9448-11e7-8638-803cec09d632.png)

#### Projetos
![image](https://user-images.githubusercontent.com/20569339/30193662-c0975074-9424-11e7-9ffc-0c2354b5d3d1.png)

#### Sobre mim
![image](https://user-images.githubusercontent.com/20569339/30193665-c43d43a0-9424-11e7-9096-6f0af7dd49fd.png)

**Comment by LFeh** [comment]
Como disse no Slack, a issue está perfeita, mas coloca no seu repositorio ;)
