### ISSUE TITLE
Adicionar uma chamada para o Code Review nesse repositório

### ISSUE THREAD

**Issue by woliveiras** [LFeh/felipefriends#7]
@LFeh, adicionei um link para esse repositório no nosso projeto [Code Review](https://github.com/training-center/code-review). 

Acha que seria interessante colocar um link para o Code Review aqui para que as pessoas saibam que podem mandar exercícios pra lá também?

**Comment by LFeh** [comment]
Claro, consegue abrir esse request?

**Comment by woliveiras** [comment]
Feiiiito
